// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  instagramUrl?: string
  facebookUrl?: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  logoUrl?: string
  photos: string[]
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  about: {
    heading: string
    body: string
    ownerName: string
  }
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'Phoenix Roofing Ltd',
  trade: 'Roofers',
  tagline: 'Bristol\'s Trusted Roofing Experts',
  phone: '+44 7361 066363',
  email: 'info@phoenixroofingltd.co.uk',
  address: '14, 15 Triangle S, Clifton, Bristol BS8 1EY, United Kingdom',
  city: 'Bristol',
  serviceArea: 'Bristol',
  googleBusinessUrl: 'https://www.google.com/maps/search/?api=1&query=Phoenix%20Roofing%20Ltd&query_place_id=ChIJsSqNZAcJdkgR1NoMOPuOumU',
  instagramUrl: 'https://www.instagram.com/aiwithdennis',
  facebookUrl: 'https://www.facebook.com/leadplug/',
  yearsExperience: 0,
  
  photos: ["https://www.phoenixroofingltd.co.uk/wp-content/uploads/elementor/thumbs/Phoenix-Roofing-Roof-Repairs-in-Surrey-London-022-pldbe6c4my8lw4947tqnis7p7uscomo8g3c2t9souo.jpeg", "https://www.phoenixroofingltd.co.uk/wp-content/uploads/elementor/thumbs/Phoenix-Roofing-Roof-Repairs-in-Surrey-London-015-pldbdytf49ybb8k1fqhmyu40grtez1udr246z23u8g.jpeg", "https://www.phoenixroofingltd.co.uk/wp-content/uploads/2022/03/Phoenix-Roofing-Roof-Repairs-in-Surrey-London-014.jpeg", "https://www.phoenixroofingltd.co.uk/wp-content/uploads/2022/03/Phoenix-Roofing-Roof-Repairs-in-Surrey-London-012.jpeg", "https://www.phoenixroofingltd.co.uk/wp-content/uploads/2022/03/Phoenix-Roofing-Roof-Repairs-in-Surrey-London-009.jpeg", "https://www.phoenixroofingltd.co.uk/wp-content/uploads/2022/03/Phoenix-Roofing-Roof-Repairs-in-Surrey-London-032.jpeg"],

  variant: 'B',

  hero: {
    heading: 'Expert Roofers Serving Bristol and Surrounding Areas',
    subheading: 'Phoenix Roofing Ltd provides professional roofing services throughout Bristol. We\'re fully insured, local roofers with a 5-star rating from over 40 satisfied customers.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix leaks, damaged tiles, and structural issues quickly and effectively. Our emergency repair service ensures your property stays protected.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Roof Replacement',
      description: 'Complete roof replacement using high-quality materials and expert installation. We handle everything from planning to cleanup.',
    },
    {
      iconName: 'Home',
      name: 'New Roof Installation',
      description: 'Professional installation of new roofing systems for extensions and new builds. We work with all roofing materials to suit your property.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough roof surveys to identify potential problems before they become costly repairs. We provide detailed reports with honest recommendations.',
    },
    {
      iconName: 'Droplets',
      name: 'Guttering Services',
      description: 'Installation, repair, and cleaning of gutters and downpipes. We ensure proper drainage to protect your property from water damage.',
    },
    {
      iconName: 'Shield',
      name: 'Roof Maintenance',
      description: 'Regular maintenance programmes to extend your roof\'s lifespan and prevent costly repairs. We keep your roof in peak condition year-round.',
    },
  ],

  trustItems: [
    'Fully Insured',
    'Free Quotes',
    'Local to Bristol',
    '5-Star Rated'
  ],

  whyUs: {
    heading: 'Why Choose Phoenix Roofing Ltd?',
    subheading: 'We\'re Bristol\'s trusted roofing specialists with a proven track record of quality workmanship and customer satisfaction.',
    points: [
      {
        heading: 'Local Expertise',
        body: 'Based in Clifton, we understand Bristol\'s unique weather challenges and building styles. Our local knowledge ensures the right solution for your property.',
      },
      {
        heading: 'Quality Materials',
        body: 'We only use premium roofing materials from trusted suppliers. This ensures your roof stands the test of time and weather.',
      },
      {
        heading: 'Fully Insured',
        body: 'Complete peace of mind with full public liability insurance. Your property and our work are fully protected.',
      },
      {
        heading: 'Honest Pricing',
        body: 'Transparent quotes with no hidden costs or surprises. You\'ll know exactly what you\'re paying for before we start.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or request a quote online to discuss your roofing needs. We\'ll arrange a convenient time to visit your property.',
    },
    {
      heading: 'Free Assessment',
      body: 'Our expert roofers will inspect your roof and provide an honest assessment. You\'ll receive a detailed quote with no obligation.',
    },
    {
      heading: 'Professional Installation',
      body: 'Our skilled team carries out the work using quality materials and proven techniques. We keep disruption to a minimum throughout the project.',
    },
    {
      heading: 'Quality Guarantee',
      body: 'We inspect all completed work to ensure it meets our high standards. Your satisfaction and the quality of our work are our top priorities.',
    },
  ],

  faqs: [
    {
      question: 'How quickly can you respond to emergency roof repairs?',
      answer: 'We offer emergency repair services and aim to respond within 24 hours for urgent leaks or storm damage. Call us immediately and we\'ll arrange emergency cover if needed.',
    },
    {
      question: 'Do you provide free quotes?',
      answer: 'Yes, we provide free, no-obligation quotes for all roofing work. Our assessment includes a thorough inspection and detailed written estimate.',
    },
    {
      question: 'What areas around Bristol do you cover?',
      answer: 'We serve Bristol and the surrounding areas including Clifton, Redland, Cotham, and nearby villages. Contact us to confirm we cover your location.',
    },
    {
      question: 'Are you fully insured?',
      answer: 'Yes, we carry full public liability insurance and employers\' liability cover. We can provide proof of insurance upon request for your peace of mind.',
    },
    {
      question: 'What roofing materials do you work with?',
      answer: 'We work with all types of roofing materials including tiles, slates, felt, and metal roofing. We\'ll recommend the best option for your property and budget.',
    },
    {
      question: 'How long does a typical roof replacement take?',
      answer: 'Most residential roof replacements take 3-7 days depending on size and complexity. We\'ll give you a clear timeline when we provide your quote.',
    },
  ],

  about: {
    heading: 'About Phoenix Roofing Ltd',
    body: 'I started Phoenix Roofing Ltd because Bristol deserves honest, reliable roofers who take pride in their work. Every roof we work on gets the same attention to detail I\'d want for my own home. I believe in doing the job right the first time and building lasting relationships with our customers throughout Bristol.',
    ownerName: 'The Phoenix Roofing Team — Owner',
  },

  reviews: [
    {
      name: 'Jimmy P.',
      rating: 5,
      text: 'Very friendly and reliable kept me informed throughout the entire job what would be happening 10/10 service',
      date: '',
    },
    {
      name: 'Glenn C.',
      rating: 5,
      text: 'Had some work done by Phoenix a few years ago and it’s still held up (as it should)! But we had a different set of leaks come up and they came out on a Sunday to look - turns out it was just moss build up but they kindly cleared it all for free.\n\nReally great to have a company that will go the extra mile to keep a customer :)',
      date: '',
    },
    {
      name: 'Love B.',
      rating: 5,
      text: '"Done a great job on my roof also repointing my chimney would highly recommend"',
      date: '',
    },
    {
      name: 'T C.',
      rating: 5,
      text: 'It’s always nerve-racking when you use a firm for the first time but I didn’t need to worry. John & the team did a great job replacing the felt & battens on my kitchen roof. The price was good, the lads were friendly, kept me informed throughout & even cleaned up after themselves. I will definitely be using them again & recommending to others.',
      date: '',
    },
    {
      name: 'Adrian M.',
      rating: 5,
      text: 'Many thanks to John and his team who replaced my slipped tiles at short notice. Would definitely recommend.',
      date: '',
    },
  ],

  seo: {
    title: 'Phoenix Roofing Ltd | Roofers in Bristol',
    description: 'Expert roofers in Bristol. Roof repairs, replacements & installations. 5-star rated, fully insured. Free quotes. Call +44 7361 066363 today.',
    canonicalUrl: 'https://preview-phoenix-roofing-ltd.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1C1C1E',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#F9F9F9',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E4E4E4',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
